#!/usr/bin/env python3
"""Validate commit messages against the Conventional Commits pattern."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import subprocess
import sys


PATTERN_TEXT = r"^((BREAKING[ -]CHANGE: )|((?i:(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test))(\([\w\-\.]+\))?(!)?: )){1}([^\r\n])+([\s\S]*)"
PATTERN = re.compile(PATTERN_TEXT)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate commit messages against the repository Conventional Commits pattern."
    )
    parser.add_argument("--base", help="Base Git revision for range validation.")
    parser.add_argument("--head", help="Head Git revision for range validation.")
    parser.add_argument("--message-file", help="Path to a commit message file.")
    return parser.parse_args()


def run_git(args: list[str]) -> str:
    result = subprocess.run(
        ["git", *args],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    return result.stdout


def is_zero_sha(value: str | None) -> bool:
    return bool(value) and set(value) == {"0"}


def commit_messages(base: str | None, head: str | None) -> list[tuple[str, str]]:
    if not head:
        head = "HEAD"

    if base and not is_zero_sha(base):
        revision = f"{base}..{head}"
    elif has_parent(head):
        revision = f"{head}^..{head}"
    else:
        revision = head

    # Merge commits are generated by GitHub and commonly use subjects such as
    # "Merge pull request ...". Validate the authored commits they contain;
    # the merge wrapper itself is not a Conventional Commit.
    output = run_git(["log", "--no-merges", "--format=%H%x1f%B%x1e", "--reverse", revision])
    messages: list[tuple[str, str]] = []
    for entry in output.split("\x1e"):
        entry = entry.strip("\n")
        if not entry:
            continue
        commit_sha, message = entry.split("\x1f", 1)
        messages.append((commit_sha, message.strip()))
    return messages


def has_parent(commit: str) -> bool:
    result = subprocess.run(
        ["git", "rev-parse", "--verify", f"{commit}^"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        text=True,
    )
    return result.returncode == 0


def validate(message: str) -> bool:
    return bool(PATTERN.match(message))


def main() -> int:
    args = parse_args()

    if args.message_file:
        message = Path(args.message_file).read_text(encoding="utf-8").strip()
        if validate(message):
            return 0
        print("Commit message does not match the Conventional Commits pattern.", file=sys.stderr)
        print(f"Required pattern: {PATTERN_TEXT}", file=sys.stderr)
        return 1

    failures = [
        (commit_sha, message.splitlines()[0] if message else "")
        for commit_sha, message in commit_messages(args.base, args.head)
        if not validate(message)
    ]

    if not failures:
        return 0

    print("Commit messages must start with the Conventional Commits pattern.", file=sys.stderr)
    print(f"Required pattern: {PATTERN_TEXT}", file=sys.stderr)
    for commit_sha, subject in failures:
        print(f"- {commit_sha[:12]} {subject}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
